Repository input-output-hk/cardano-js-sdk, pull requests merged in 2022-08, with the labels that each got.

#383 Test/e2e wallet NFT fix
  packages/e2e/test/wallet/SingleAddressWallet/nft.test.ts
Labels: test

#385 feat!: replace `NetworkInfoProvider.timeSettings` with `eraSummaries`
  packages/blockfrost/src/blockfrostNetworkInfoProvider.ts
  packages/blockfrost/src/util.ts
  packages/blockfrost/test/blockfrostNetworkInfoProvider.test.ts
  packages/cardano-services-client/src/NetworkInfoProvider/networkInfoHttpProvider.ts
  packages/cardano-services-client/test/NetworkInfo/networkInfoHttpProvider.test.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/DbSyncNetworkInfoProvider.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
  packages/cardano-services/src/NetworkInfo/NetworkInfoHttpService.ts
  packages/cardano-services/src/NetworkInfo/openApi.json
  packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
  packages/core/src/Provider/NetworkInfoProvider/types.ts
  packages/core/src/util/slotCalc.ts
  packages/core/test/util/slotCalc.test.ts
  packages/ogmios/test/CardanoNode/mappers.test.ts
  packages/wallet/src/SingleAddressWallet.ts
  packages/wallet/src/persistence/inMemoryStores/inMemoryWalletStores.ts
  packages/wallet/src/persistence/pouchDbStores/pouchDbWalletStores.ts
  packages/wallet/src/persistence/types.ts
  packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
  packages/wallet/src/services/EpochTracker.ts
  packages/wallet/src/services/ProviderTracker/ProviderStatusTracker.ts
  packages/wallet/src/services/ProviderTracker/TrackedWalletNetworkInfoProvider.ts
  packages/wallet/src/services/util/equals.ts
  packages/wallet/src/services/util/trigger.ts
  packages/wallet/src/types.ts
  packages/wallet/test/SingleAddressWallet/load.test.ts
  packages/wallet/test/integration/transactionTime.test.ts
  packages/wallet/test/mocks/mockNetworkInfoProvider.ts
  packages/wallet/test/mocks/mockNetworkInfoProvider2.ts
  packages/wallet/test/persistence/inMemoryStores.test.ts
  packages/wallet/test/services/EpochTracker.test.ts
  packages/wallet/test/services/ProviderTracker/TrackedWalletNetworkInfoProvider.test.ts
  packages/wallet/test/services/util/equals.test.ts
  packages/wallet/test/services/util/trigger.test.ts
  packages/web-extension/src/observableWallet/util.ts
Labels: refactor

#409 build: move docker-compose service ENVs into compose files
  Dockerfile
  packages/cardano-services/docker-compose.yml
  packages/e2e/docker-compose.yml
Labels: build

#403 feat: Enhance /metrics with custom HTTP server wide HealthCheckResponse
  packages/cardano-services/src/Http/HttpServer.ts
  packages/cardano-services/test/Http/HttpServer.test.ts
Labels: feat

#404 feat: Allow signing transactions with arbitrary keys
  packages/core/package.json
  packages/core/src/CSL/coreToCsl/coreToCsl.ts
  packages/core/src/CSL/cslToCore/cslToCore.ts
  packages/core/src/Cardano/types/Asset.ts
  packages/core/src/Cardano/types/Key.ts
  packages/core/src/Cardano/types/Script.ts
  packages/core/src/Cardano/util/index.ts
  packages/core/src/Cardano/util/metadatum.ts
  packages/core/src/Cardano/util/nativeScript.ts
  packages/core/src/errors.ts
  packages/core/test/Cardano/types/Asset.test.ts
  packages/core/test/Cardano/types/Key.test.ts
  packages/core/test/Cardano/util/metadatum.test.ts
  packages/core/test/util/nativeScript.test.ts
  packages/e2e/docker-compose.yml
  packages/e2e/local-network/scripts/install.sh
  packages/e2e/src/FaucetProvider/providers/cardanoWalletFaucetProvider.ts
  packages/e2e/test/cardano-services/load/load.test.ts
  packages/e2e/test/local-network/local-network.test.ts
  packages/e2e/test/wallet/SingleAddressWallet/delegation.test.ts
  packages/e2e/test/wallet/SingleAddressWallet/metadata.test.ts
  packages/e2e/test/wallet/SingleAddressWallet/multisginature.test.ts
  packages/e2e/test/wallet/SingleAddressWallet/txChaining.test.ts
  packages/e2e/test/web-extension/extension/ui.ts
  packages/wallet/src/KeyManagement/InMemoryKeyAgent.ts
  packages/wallet/src/KeyManagement/errors/ProofGenerationError.ts
  packages/wallet/src/KeyManagement/errors/index.ts
  packages/wallet/src/KeyManagement/types.ts
  packages/wallet/src/KeyManagement/util/KeyAgentTransactionSigner.ts
  packages/wallet/src/KeyManagement/util/index.ts
  packages/wallet/src/KeyManagement/util/stubSignTransaction.ts
  packages/wallet/src/SingleAddressWallet.ts
  packages/wallet/src/cip30.ts
  packages/wallet/src/types.ts
  packages/wallet/test/KeyManagement/util/stubSignTransaction.test.ts
  packages/wallet/test/SingleAddressWallet/methods.test.ts
  packages/wallet/test/integration/cip30mapping.test.ts
  packages/wallet/test/integration/txChainingBalance.test.ts
  packages/wallet/test/integration/withdrawal.test.ts
  yarn-project.nix
  yarn.lock
Labels: feat
