Repository input-output-hk/cardano-js-sdk, pull requests merged in 2022-11, with the labels that each got.

#490 feat: Support Stake Pool Extended Metadata
  packages/cardano-services/copy-assets.sh
  packages/cardano-services/package.json
  packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
  packages/cardano-services/src/Asset/DbSyncNftMetadataService.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
  packages/cardano-services/src/Metadata/DbSyncMetadataService.ts
  packages/cardano-services/src/Metadata/types.ts
  packages/cardano-services/src/Program/loadHttpServer.ts
  packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
  packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
  packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
  packages/cardano-services/src/StakePool/HttpStakePoolMetadata/HttpStakePoolExtMetadataService.ts
  packages/cardano-services/src/StakePool/HttpStakePoolMetadata/index.ts
  packages/cardano-services/src/StakePool/HttpStakePoolMetadata/mappers.ts
  packages/cardano-services/src/StakePool/HttpStakePoolMetadata/schemas/ada-pools.json
  packages/cardano-services/src/StakePool/HttpStakePoolMetadata/schemas/cip-6.json
  packages/cardano-services/src/StakePool/HttpStakePoolMetadata/types.ts
  packages/cardano-services/src/StakePool/HttpStakePoolMetadata/util.ts
  packages/cardano-services/src/StakePool/index.ts
  packages/cardano-services/src/StakePool/openApi.json
  packages/cardano-services/src/StakePool/types.ts
  packages/cardano-services/test/Asset/AssetBuilder.test.ts
  packages/cardano-services/test/Asset/AssetHttpService.test.ts
  packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
  packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
  packages/cardano-services/test/Asset/DbSyncNftMetadataService.test.ts
  packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
  packages/cardano-services/test/Metadata/DbSyncMetadataService.test.ts
  packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.test.ts
  packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
  packages/cardano-services/test/Program/services/ogmios.test.ts
  packages/cardano-services/test/Program/services/postgres.test.ts
  packages/cardano-services/test/Program/services/rabbitmq.test.ts
  packages/cardano-services/test/Reward/DbSyncRewardsProvider/RewardsBuilder.test.ts
  packages/cardano-services/test/Reward/RewardsHttpService.test.ts
  packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
  packages/cardano-services/test/StakePool/HttpStakePoolMetadataService/HttpMetadataService.test.ts
  packages/cardano-services/test/StakePool/HttpStakePoolMetadataService/__snapshots__/HttpMetadataService.test.ts.snap
  packages/cardano-services/test/StakePool/HttpStakePoolMetadataService/mocks.ts
  packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
  packages/cardano-services/test/TxSubmit/TxSubmitHttpService.test.ts
  packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
  packages/cardano-services/test/cli.test.ts
  packages/cardano-services/test/util/provider.test.ts
  packages/core/src/Cardano/types/StakePool/ExtendedStakePoolMetadata.ts
  packages/core/src/Cardano/types/StakePool/PoolParameters.ts
  packages/util-dev/package.json
  packages/util-dev/src/createGenericMockServer.ts
  packages/util-dev/src/index.ts
  yarn-project.nix
  yarn.lock
Labels: feat

#511 ci: Remove Node.js latest testing from nightly workflow
  .github/workflows/nightly-test.yaml
Labels: ci

#509 refactor: align CardanoNode and TxSubmitProvider as runnable modules
  packages/cardano-services-client/src/TxSubmitProvider/txSubmitHttpProvider.ts
  packages/cardano-services-client/test/TxSubmitProvider/txSubmitHttpProvider.test.ts
  packages/cardano-services/src/Http/HttpServer.ts
  packages/cardano-services/src/Program/services/ogmios.ts
  packages/cardano-services/src/Program/services/rabbitmq.ts
  packages/cardano-services/src/TxSubmit/rabbitmq/RabbitMqTxSubmitProvider.ts
  packages/cardano-services/src/TxSubmit/rabbitmq/TxSubmitWorker.ts
  packages/cardano-services/src/TxSubmit/rabbitmq/utils.ts
  packages/cardano-services/src/cli.ts
  packages/cardano-services/test/Program/services/ogmios.test.ts
  packages/cardano-services/test/Program/services/rabbitmq.test.ts
  packages/cardano-services/test/TxSubmit/TxSubmitHttpService.test.ts
  packages/cardano-services/test/TxSubmit/rabbitmq/TxSubmitWorker.test.ts
  packages/cardano-services/test/TxSubmit/rabbitmq/rabbitmqTxSubmitProvider.test.ts
  packages/core/src/Cardano/types/TxSubmissionErrors.ts
  packages/core/src/Cardano/types/index.ts
  packages/core/src/Cardano/util/txSubmissionErrors.ts
  packages/core/src/CardanoNode/types/CardanoNode.ts
  packages/core/src/CardanoNode/types/CardanoNodeErrors.ts
  packages/core/src/Provider/TxSubmitProvider/types.ts
  packages/core/test/Cardano/types/TxSubmissionErrors.test.ts
  packages/core/test/Cardano/util/txSubmissionErrors.test.ts
  packages/core/test/CardanoNode/util/cardanoNodeErrors.test.ts
  packages/e2e/src/factories.ts
  packages/e2e/test/web-extension/extension/background/config.ts
  packages/ogmios/src/CardanoNode/OgmiosCardanoNode.ts
  packages/ogmios/src/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.ts
  packages/ogmios/src/Provider/TxSubmitProvider/index.ts
  packages/ogmios/src/Provider/TxSubmitProvider/ogmiosTxSubmitProvider.ts
  packages/ogmios/test/CardanoNode/OgmiosCardanoNode.test.ts
  packages/ogmios/test/CardanoNode/__snapshots__/OgmiosCardanoNode.test.ts.snap
  packages/ogmios/test/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.test.ts
  packages/ogmios/test/mocks/mockOgmiosServer.ts
  packages/ogmios/test/mocks/types.ts
  packages/ogmios/test/mocks/util.ts
  packages/ogmios/test/util.test.ts
  packages/wallet/src/SingleAddressWallet/SingleAddressWallet.ts
  packages/wallet/src/services/SmartTxSubmitProvider.ts
  packages/wallet/src/services/types.ts
  packages/wallet/src/types.ts
  packages/wallet/test/SingleAddressWallet/methods.test.ts
  packages/wallet/test/integration/buildTx.test.ts
Labels: refactor
