Repository input-output-hk/cardano-js-sdk, pull requests merged in 2022-07, with the labels that each got.

#294 chore: Dockerize cardano-services http-server, extend docker-compose services
  .dockerignore
  .github/workflows/continuous-integration.yaml
  Dockerfile
  docker-compose.yml
  package.json
  packages/cardano-services/docker-compose.yml
  packages/cardano-services/package.json
  packages/cardano-services/placeholder-secrets/postgres_db
  packages/cardano-services/placeholder-secrets/postgres_password
  packages/cardano-services/placeholder-secrets/postgres_user
  packages/cardano-services/src/ProgramsCommon/defaults.ts
  packages/cardano-services/src/run.ts
Labels: chore

#298 feature/ADP-1901 - Ogmios time settings
  packages/cardano-services/.env.test
  packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/DbSyncNetworkInfoProvider.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/keys.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/utils.ts
  packages/cardano-services/src/Program/ProgramOptionDescriptions.ts
  packages/cardano-services/src/Program/loadHttpServer.ts
  packages/cardano-services/src/cli.ts
  packages/cardano-services/src/run.ts
  packages/cardano-services/src/util/validators.ts
  packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
  packages/cardano-services/test/NetworkInfo/__snapshots__/NetworkInfoHttpService.test.ts.snap
  packages/cardano-services/test/Program/loadHttpServer.test.ts
  packages/cardano-services/test/entrypoints.test.ts
  packages/cardano-services/test/entrypoints.txWorker.test.ts
  packages/cardano-services/test/util.ts
  packages/core/src/CardanoNode/index.ts
  packages/core/src/CardanoNode/types/CardanoNode.ts
  packages/core/src/CardanoNode/types/CardanoNodeErrors.ts
  packages/core/src/CardanoNode/types/index.ts
  packages/core/src/CardanoNode/util/cardanoNodeErrors.ts
  packages/core/src/CardanoNode/util/index.ts
  packages/core/src/index.ts
  packages/core/test/Cardano/util/txSubmissionErrors.test.ts
  packages/core/test/CardanoNode/util/cardanoNodeErrors.test.ts
  packages/ogmios/src/CardanoNode/OgmiosCardanoNode.ts
  packages/ogmios/src/CardanoNode/index.ts
  packages/ogmios/src/CardanoNode/mappers.ts
  packages/ogmios/src/Provider/TxSubmitProvider/index.ts
  packages/ogmios/src/Provider/TxSubmitProvider/ogmiosTxSubmitProvider.ts
  packages/ogmios/src/Provider/index.ts
  packages/ogmios/src/index.ts
  packages/ogmios/src/util.ts
  packages/ogmios/test/CardanoNode/OgmiosCardanoNode.test.ts
  packages/ogmios/test/CardanoNode/__snapshots__/OgmiosCardanoNode.test.ts.snap
  packages/ogmios/test/CardanoNode/mappers.test.ts
  packages/ogmios/test/Provider/TxSubmitProvider/ogmiosTxSubmitProvider.test.ts
  packages/ogmios/test/mocks/mockOgmiosServer.ts
Labels: feat

#324 feat: add missing transaction fields
  packages/wallet/src/SingleAddressWallet.ts
  packages/wallet/src/Transaction/createTransactionInternals.ts
  packages/wallet/src/types.ts
  packages/wallet/test/SingleAddressWallet/methods.test.ts
  packages/wallet/test/Transaction/createTransactionInternals.test.ts
Labels: feat

#309 feat: cardano-services dependency port resolution using DNS SRV records
  packages/cardano-services/.env.test
  packages/cardano-services/package.json
  packages/cardano-services/src/Program/ProgramOptionDescriptions.ts
  packages/cardano-services/src/Program/errors/InvalidArgsCombination.ts
  packages/cardano-services/src/Program/errors/MissingProgramOption.ts
  packages/cardano-services/src/Program/errors/index.ts
  packages/cardano-services/src/Program/index.ts
  packages/cardano-services/src/Program/loadHttpServer.ts
  packages/cardano-services/src/Program/utils.ts
  packages/cardano-services/src/ProgramsCommon/CommonOptionDescriptions.ts
  packages/cardano-services/src/ProgramsCommon/options.ts
  packages/cardano-services/src/TxWorker/loadTxWorker.ts
  packages/cardano-services/src/cli.ts
  packages/cardano-services/src/run.ts
  packages/cardano-services/src/startWorker.ts
  packages/cardano-services/test/Program/loadHttpServer.test.ts
  packages/cardano-services/test/Program/utils.test.ts
  packages/cardano-services/test/entrypoints.test.ts
  packages/cardano-services/test/entrypoints.txWorker.test.ts
  yarn.lock
Labels: feat

#334 test(e2e): fix Blockfrost e2e breaking tests due to Babbage era changes
  packages/e2e/test/blockfrost/queryTransactions.test.ts
Labels: test

#346 Make all providers extend Provider, and fix HTTP service dependency types
  packages/blockfrost/src/blockfrostAssetProvider.ts
  packages/blockfrost/src/blockfrostChainHistoryProvider.ts
  packages/blockfrost/src/blockfrostNetworkInfoProvider.ts
  packages/blockfrost/src/blockfrostRewardsProvider.ts
  packages/blockfrost/src/blockfrostTxSubmitProvider.ts
  packages/blockfrost/src/blockfrostUtxoProvider.ts
  packages/blockfrost/src/util.ts
  packages/cardano-services-client/src/AssetInfoProvider/assetInfoHttpProvider.ts
  packages/cardano-services-client/src/NetworkInfoProvider/networkInfoHttpProvider.ts
  packages/cardano-services-client/src/StakePoolProvider/stakePoolHttpProvider.ts
  packages/cardano-services/src/ChainHistory/ChainHistoryHttpService.ts
  packages/cardano-services/src/NetworkInfo/NetworkInfoHttpService.ts
  packages/cardano-services/src/Rewards/RewardsHttpService.ts
  packages/cardano-services/src/StakePool/StakePoolHttpService.ts
  packages/cardano-services/src/Utxo/UtxoHttpService.ts
  packages/core/src/Provider/AssetProvider/types.ts
  packages/core/src/Provider/NetworkInfoProvider/types.ts
  packages/core/src/Provider/StakePoolProvider/types/StakePoolProvider.ts
  packages/e2e/src/FaucetProvider/providers/cardanoWalletFaucetProvider.ts
  packages/e2e/src/factories.ts
  packages/util-dev/src/createStubStakePoolProvider.ts
  packages/wallet/src/services/ProviderTracker/TrackedAssetProvider.ts
  packages/wallet/src/services/ProviderTracker/TrackedNetworkInfoProvider.ts
  packages/wallet/src/services/ProviderTracker/TrackedStakePoolProvider.ts
  packages/wallet/test/mocks/mockAssetProvider.ts
  packages/wallet/test/mocks/mockNetworkInfoProvider.ts
  packages/wallet/test/mocks/mockNetworkInfoProvider2.ts
  packages/wallet/test/services/ProviderTracker/TrackedAssetProvider.test.ts
  packages/wallet/test/services/ProviderTracker/TrackedChainHistoryProvider.test.ts
  packages/wallet/test/services/ProviderTracker/TrackedNetworkInfoProvider.test.ts
  packages/wallet/test/services/ProviderTracker/TrackedRewardsProvider.test.ts
  packages/wallet/test/services/ProviderTracker/TrackedStakePoolProvider.test.ts
  packages/wallet/test/services/ProviderTracker/TrackedUtxoProvider.test.ts
Labels: fix, refactor, test, docs

#321 feat(cardano-services): adds asset http service
  packages/cardano-services-client/test/AssetInfoProvider/assetInfoHttpProvider.test.ts
  packages/cardano-services/copy-assets.sh
  packages/cardano-services/src/Asset/AssetHttpService.ts
  packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
  packages/cardano-services/src/Asset/DbSyncAssetProvider.ts
  packages/cardano-services/src/Asset/index.ts
  packages/cardano-services/src/Asset/openApi.json
  packages/cardano-services/src/Http/HttpService.ts
  packages/cardano-services/src/Program/ProgramOptionDescriptions.ts
  packages/cardano-services/src/Program/ServiceNames.ts
  packages/cardano-services/src/Program/loadHttpServer.ts
  packages/cardano-services/src/Program/utils.ts
  packages/cardano-services/src/ProgramsCommon/CommonOptionDescriptions.ts
  packages/cardano-services/src/TxWorker/loadTxWorker.ts
  packages/cardano-services/src/cli.ts
  packages/cardano-services/src/index.ts
  packages/cardano-services/src/run.ts
  packages/cardano-services/test/Asset/AssetBuilder.test.ts
  packages/cardano-services/test/Asset/AssetHttpService.test.ts
  packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
  packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
  packages/cardano-services/test/Program/utils.test.ts
  packages/cardano-services/test/entrypoints.test.ts
Labels: feat, refactor

#344 feat: service discovery error handling for TxSubmitWorker
  packages/cardano-services/src/Program/utils.ts
  packages/cardano-services/src/TxWorker/loadTxWorker.ts
  packages/cardano-services/src/TxWorker/utils.ts
  packages/cardano-services/src/cli.ts
  packages/cardano-services/src/startWorker.ts
  packages/cardano-services/test/Program/utils.test.ts
  packages/cardano-services/test/TxWorker/utils.test.ts
  packages/cardano-services/test/entrypoints.txWorker.test.ts
  packages/rabbitmq/src/TxSubmitWorker.ts
  packages/rabbitmq/src/utils.ts
  packages/rabbitmq/test/TxSubmitWorker.test.ts
Labels: feat

#352 refactor(cardano-services): CLI improvements in cardano-services
  packages/cardano-services/.env.test
  packages/cardano-services/docker-compose.yml
  packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
  packages/cardano-services/src/InMemoryCache/defaults.ts
  packages/cardano-services/src/Program/ProgramOptionDescriptions.ts
  packages/cardano-services/src/Program/loadHttpServer.ts
  packages/cardano-services/src/Program/utils.ts
  packages/cardano-services/src/ProgramsCommon/CommonOptionDescriptions.ts
  packages/cardano-services/src/ProgramsCommon/options.ts
  packages/cardano-services/src/cli.ts
  packages/cardano-services/src/run.ts
  packages/cardano-services/src/startWorker.ts
  packages/cardano-services/src/util/validators.ts
  packages/cardano-services/test/Asset/AssetBuilder.test.ts
  packages/cardano-services/test/Asset/AssetHttpService.test.ts
  packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
  packages/cardano-services/test/Asset/DbSyncNftMetadataService.test.ts
  packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
  packages/cardano-services/test/Http/HttpServer.test.ts
  packages/cardano-services/test/InMemoryCache/InMemoryCache.test.ts
  packages/cardano-services/test/Metadata/DbSyncMetadataService.test.ts
  packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.test.ts
  packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
  packages/cardano-services/test/Program/loadHttpServer.test.ts
  packages/cardano-services/test/Program/utils.test.ts
  packages/cardano-services/test/Reward/DbSyncRewardsProvider/RewardsBuilder.test.ts
  packages/cardano-services/test/Reward/RewardsHttpService.test.ts
  packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
  packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
  packages/cardano-services/test/TxWorker/utils.test.ts
  packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
  packages/cardano-services/test/entrypoints.test.ts
  packages/cardano-services/test/jest-setup/jest-setup.ts
  packages/e2e/docker-compose.yml
Labels: refactor

#345 fix(blockfrost): handle arrays in image and description fields
  packages/blockfrost/src/blockfrostAssetProvider.ts
  packages/blockfrost/test/blockfrostAssetProvider.test.ts
Labels: fix

#326 feat: implement cip30 getCollateral
  packages/cip30/src/WalletApi/types.ts
  packages/wallet/src/cip30.ts
  packages/wallet/test/integration/cip30mapping.test.ts
  packages/wallet/test/integration/util.ts
  packages/wallet/test/mocks/mockData.ts
Labels: feat
