Repository input-output-hk/cardano-js-sdk, pull requests merged in 2022-09, with the labels that each got.

#413 Fix --use-queue arg parser
  packages/cardano-services/src/cli.ts
  packages/cardano-services/test/cli.test.ts
  packages/cardano-services/test/entrypoints.test.ts
  packages/cardano-services/test/entrypoints.txWorker.test.ts
  packages/e2e/test/cardano-services/load/load.test.ts
Labels: bug, test

#424 Feat/add e2e tests to CI
  .github/workflows/continuous-integration.yaml
  packages/e2e/README.md
  packages/e2e/jest.config.js
  packages/e2e/package.json
  packages/e2e/test/load-testing/tx-submit-load.test.ts
  packages/e2e/test/wallet/SingleAddressWallet/delegation.test.ts
  packages/e2e/test/wallet/SingleAddressWallet/multisignature.test.ts
  packages/e2e/test/wallet/environment.ts
Labels: ci

#416 fix: Remove nullability of ProtocolParametersBabbage properties
  packages/blockfrost/src/BlockfrostToCore.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/queries.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/types.ts
  packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/__snapshots__/NetworkInfoBuilder.test.ts.snap
  packages/cip2/src/types.ts
  packages/core/src/Cardano/types/ProtocolParameters.ts
  packages/core/src/Cardano/types/Script.ts
  packages/core/src/Provider/NetworkInfoProvider/types.ts
Labels: fix

#412 fix: Gracefully handle `CardanoTokenRegistry` errors during `getAsset` request
  packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
  packages/cardano-services/src/Asset/DbSyncAssetProvider.ts
  packages/cardano-services/src/Asset/openApi.json
  packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
  packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
Labels: fix

#433 feat: calculate stability window slots count in wallet
  packages/core/src/util/calcStabilityWindow.ts
  packages/core/src/util/index.ts
  packages/core/test/util/calcStabilityWindow.test.ts
  packages/wallet/src/SingleAddressWallet.ts
  packages/wallet/src/services/TransactionReemitter.ts
  packages/wallet/test/SingleAddressWallet/rollback.test.ts
  packages/wallet/test/services/TransactionReemiter.test.ts
Labels: feat

#453 docs: update README workflow badges
  .github/workflows/nightly.yaml
  README.md
Labels: docs

#460 fix(cardano-services): wrong tx onput `txId` value
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
  packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/__snapshots__/ChainHistoryBuilder.test.ts.snap
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
  packages/cardano-services/test/ChainHistory/__snapshots__/ChainHistoryHttpService.test.ts.snap
  packages/e2e/test/wallet/SingleAddressWallet/txChainHistory.test.ts
  packages/e2e/test/wallet/util.ts
Labels: fix

#455 Fix/Ogmios WebSocket close logging
  packages/ogmios/src/CardanoNode/OgmiosCardanoNode.ts
  packages/ogmios/src/Provider/TxSubmitProvider/ogmiosTxSubmitProvider.ts
  packages/ogmios/src/util.ts
  packages/ogmios/test/util.test.ts
Labels: bug, feat
