Repository input-output-hk/cardano-js-sdk, pull requests merged in 2022-06, with the labels that each got.

#251 feature(wallet): Trezor Hardware Wallet Transaction Signing
  packages/wallet/src/KeyManagement/LedgerKeyAgent.ts
  packages/wallet/src/KeyManagement/TrezorKeyAgent.ts
  packages/wallet/src/KeyManagement/types.ts
  packages/wallet/src/KeyManagement/util/constants.ts
  packages/wallet/src/KeyManagement/util/index.ts
  packages/wallet/src/KeyManagement/util/key.ts
  packages/wallet/src/KeyManagement/util/mapHardwareSigningData.ts
  packages/wallet/test/KeyManagement/restoreKeyAgent.test.ts
  packages/wallet/test/e2e/config.ts
  packages/wallet/test/hardware/LedgerKeyAgent.integration.test.ts
  packages/wallet/test/hardware/LedgerKeyAgent.test.ts
  packages/wallet/test/hardware/TrezorKeyAgent.integration.test.ts
  packages/wallet/test/hardware/TrezorKeyAgent.test.ts
Labels: enhancement

#290 fix/rabbitmq-wrong-interface
  packages/cardano-services/src/Program/loadHttpServer.ts
  packages/cardano-services/src/ProgramsCommon/defaults.ts
  packages/cardano-services/src/ProgramsCommon/errors/WrongOption.ts
  packages/cardano-services/src/ProgramsCommon/errors/index.ts
  packages/cardano-services/src/ProgramsCommon/index.ts
  packages/cardano-services/src/ProgramsCommon/programs.ts
  packages/cardano-services/src/TxWorker/errors/WrongTxWorkerOption.ts
  packages/cardano-services/src/TxWorker/errors/index.ts
  packages/cardano-services/src/TxWorker/index.ts
  packages/cardano-services/src/cli.ts
  packages/cardano-services/src/run.ts
  packages/cardano-services/test/entrypoints.txWorker.test.ts
  packages/cardano-services/test/load/load.test.ts
  packages/core/src/Cardano/util/deserializeTx.ts
  packages/core/src/Cardano/util/index.ts
  packages/core/test/Cardano/util/deserializeTx.test.ts
  packages/ogmios/test/mocks/mockOgmiosServer.ts
  packages/rabbitmq/package.json
  packages/rabbitmq/src/TxSubmitWorker.ts
  packages/rabbitmq/src/index.ts
  packages/rabbitmq/src/rabbitmqTxSubmitProvider.ts
  packages/rabbitmq/src/tsconfig.json
  packages/rabbitmq/src/utils.ts
  packages/rabbitmq/test/TxSubmitWorker.test.ts
  packages/rabbitmq/test/jest-setup/docker.ts
  packages/rabbitmq/test/rabbitmqTxSubmitProvider.test.ts
  packages/rabbitmq/test/transactions.txt
  packages/rabbitmq/test/utils.ts
  yarn.lock
Labels: fix

#304 chore: upgrade to Ogmios 5.4.0
  docker-compose.yml
  packages/cardano-services-client/package.json
  packages/core/package.json
  packages/core/src/Cardano/types/Transaction.ts
  packages/core/src/Cardano/types/TxSubmissionErrors.ts
  packages/core/test/Cardano/types/TxSubmissionErrors.test.ts
  packages/ogmios/package.json
  packages/ogmios/src/ogmiosTxSubmitProvider.ts
  packages/ogmios/test/mocks/mockOgmiosServer.ts
  packages/rabbitmq/package.json
  packages/wallet/package.json
  yarn.lock
Labels: chore

#301 refactor: Remodel NetworkInfoProvider to remove NetworkInfo
  packages/blockfrost/src/blockfrostNetworkInfoProvider.ts
  packages/blockfrost/src/util.ts
  packages/blockfrost/test/blockfrostNetworkInfoProvider.test.ts
  packages/cardano-services-client/src/NetworkInfoProvider/networkInfoHttpProvider.ts
  packages/cardano-services-client/test/NetworkInfo/networkInfoHttpProvider.test.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/DbSyncNetworkInfoProvider.ts
  packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
  packages/cardano-services/src/NetworkInfo/NetworkInfoHttpService.ts
  packages/cardano-services/src/NetworkInfo/openApi.json
  packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
  packages/cardano-services/test/NetworkInfo/__snapshots__/NetworkInfoHttpService.test.ts.snap
  packages/core/src/Cardano/types/Genesis.ts
  packages/core/src/Provider/NetworkInfoProvider/types.ts
  packages/wallet/src/SingleAddressWallet.ts
  packages/wallet/src/cip30.ts
  packages/wallet/src/persistence/inMemoryStores/inMemoryWalletStores.ts
  packages/wallet/src/persistence/pouchdbStores/pouchdbWalletStores.ts
  packages/wallet/src/persistence/types.ts
  packages/wallet/src/services/EpochTracker.ts
  packages/wallet/src/services/ProviderTracker/ProviderStatusTracker.ts
  packages/wallet/src/services/ProviderTracker/TrackedNetworkInfoProvider.ts
  packages/wallet/src/services/util/trigger.ts
  packages/wallet/src/types.ts
  packages/wallet/test/SingleAddressWallet/load.test.ts
  packages/wallet/test/integration/transactionTime.test.ts
  packages/wallet/test/mocks/mockData.ts
  packages/wallet/test/mocks/mockNetworkInfoProvider.ts
  packages/wallet/test/mocks/mockNetworkInfoProvider2.ts
  packages/wallet/test/persistence/inMemoryStores.test.ts
  packages/wallet/test/services/EpochTracker.test.ts
  packages/wallet/test/services/ProviderTracker/TrackedNetworkInfoProvider.test.ts
  packages/wallet/test/services/util/trigger.test.ts
  packages/web-extension/src/observableWallet/util.ts
Labels: refactor

#307 Ci/git checks
  .github/workflows/git-checks.yaml
Labels: ci

#297 feat: dbsync nft metadata service
  packages/cardano-services/src/Asset/DbSyncNftMetadataService.ts
  packages/cardano-services/src/Asset/index.ts
  packages/cardano-services/src/Asset/queries.ts
  packages/cardano-services/src/Asset/types.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
  packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
  packages/cardano-services/src/Metadata/DbSyncMetadataService.ts
  packages/cardano-services/src/Metadata/index.ts
  packages/cardano-services/src/Metadata/mappers.ts
  packages/cardano-services/src/Metadata/queries.ts
  packages/cardano-services/src/Metadata/types.ts
  packages/cardano-services/src/Program/loadHttpServer.ts
  packages/cardano-services/test/Asset/DbSyncNftMetadataService.test.ts
  packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/__snapshots__/ChainHistoryBuilder.test.ts.snap
  packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
  packages/cardano-services/test/Metadata/DbSyncMetadataService.test.ts
  packages/cardano-services/test/Metadata/__snapshots__/DbSyncMetadataService.test.ts.snap
  packages/cardano-services/test/Metadata/mappers.test.ts
  packages/core/src/Asset/types/NftMetadata.ts
  packages/core/test/Asset/NftMetadata.test.ts
Labels: feat
