Repository input-output-hk/cardano-js-sdk, pull requests merged in 2023-08, with the labels that each got.

#840 chore(hardware-trezor): add trezor mint bundle mapper
  packages/hardware-trezor/src/transformers/assets.ts
  packages/hardware-trezor/src/transformers/tx.ts
Labels: chore

#851 LW-7811(hardware-trezor) additional witness requests mapper
  packages/hardware-trezor/package.json
  packages/hardware-trezor/src/transformers/additionalWitnessRequests.ts
  packages/hardware-trezor/src/transformers/tx.ts
  packages/hardware-trezor/test/transformers/additionalWitnessRequests.test.ts
  packages/hardware-trezor/test/transformers/assets.test.ts
  yarn.lock
Labels: chore

#884 chore(hardware-trezor): update to dedicated trezor node and web packages [LW-7776]
  packages/hardware-trezor/package.json
  packages/hardware-trezor/src/TrezorKeyAgent.ts
  packages/hardware-trezor/src/transformers/additionalWitnessRequests.ts
  packages/hardware-trezor/src/transformers/assets.ts
  packages/hardware-trezor/src/transformers/auxiliaryData.ts
  packages/hardware-trezor/src/transformers/certificates.ts
  packages/hardware-trezor/src/transformers/tx.ts
  packages/hardware-trezor/src/transformers/txIn.ts
  packages/hardware-trezor/src/transformers/txOut.ts
  packages/hardware-trezor/src/transformers/withdrawals.ts
  packages/hardware-trezor/src/types.ts
  packages/hardware-trezor/test/transformers/certificates.test.ts
  packages/hardware-trezor/test/transformers/txOut.test.ts
  yarn.lock
Labels: chore, dependencies

#880 lw-7089: fix trezor transaction mismatching issue
  packages/hardware-trezor/src/TrezorKeyAgent.ts
  packages/key-management/src/TrezorKeyAgent.ts
  packages/wallet/test/hardware/trezor/TrezorKeyAgent.test.ts
Labels: bug
