Repository input-output-hk/cardano-js-sdk, pull requests merged in 2024-05, with the labels that each got.

#1211 [LW-10219] Ledger: Sign new certificate types
  packages/hardware-ledger/src/LedgerKeyAgent.ts
  packages/hardware-ledger/src/transformers/certificates.ts
  packages/hardware-ledger/src/transformers/index.ts
  packages/hardware-ledger/src/transformers/tx.ts
  packages/hardware-ledger/src/transformers/withdrawals.ts
  packages/hardware-ledger/test/testData.ts
  packages/hardware-ledger/test/transformers/certificates.test.ts
  packages/hardware-ledger/test/transformers/tx.test.ts
  packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
Labels: feat

#1237 chore: votingProcedures improvements and tests
  packages/core/src/Cardano/types/Governance.ts
  packages/hardware-ledger/src/LedgerKeyAgent.ts
  packages/hardware-ledger/src/transformers/votingProcedures.ts
  packages/hardware-ledger/src/transformers/withdrawals.ts
  packages/hardware-ledger/test/testData.ts
  packages/hardware-ledger/test/transformers/votingprocedures.test.ts
  packages/hardware-ledger/test/transformers/withdrawals.test.ts
  packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
Labels: chore

#1247 test(wallet): fix failing conway-era Ledger tests
  packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
Labels: test
